import { Orders } from "@/types";

export const orders: Orders[] = [
  {
    id: "1",
    customerName: "Customer 1",
    orderType: "Pickup",
    total: 100,
    status: "Pending",
    createdAt: "2022-01-01",
  },
  {
    id: "2",
    customerName: "Customer 2",
    orderType: "Delivery",
    total: 200,
    status: "Completed",
    createdAt: "2023-09-02",
  },
  {
    id: "3",
    customerName: "Customer 3",
    orderType: "Pickup",
    total: 300,
    status: "Pending",
    createdAt: "2025-09-03",
  },
  {
    id: "4",
    customerName: "Customer 4",
    orderType: "Delivery",
    total: 400,
    status: "Completed",
    createdAt: "2022-09-04",
  },
  {
    id: "5",
    customerName: "Customer 5",
    orderType: "Pickup",
    total: 500,
    status: "Pending",
    createdAt: "2020-09-05",
  },
  {
    id: "6",
    customerName: "Customer 6",
    orderType: "Delivery",
    total: 600,
    status: "Completed",
    createdAt: "2021-09-06",
  },
  {
    id: "7",
    customerName: "Customer 7",
    orderType: "Pickup",
    total: 700,
    status: "Pending",
    createdAt: "2023-08-07",
  },
  {
    id: "8",
    customerName: "Customer 8",
    orderType: "Delivery",
    total: 800,
    status: "Completed",
    createdAt: "2021-07-08",
  },
  {
    id: "9",
    customerName: "Customer 9",
    orderType: "Pickup",
    total: 900,
    status: "Pending",
    createdAt: "2022-02-09",
  },
];
